export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="darkblood2"
plugins=(git history)

source $ZSH/oh-my-zsh.sh
source "$HOME/.cargo/env"
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

alias ls="exa -al --color=always --group-directories-first --icons"
alias neofetch="neofetch --ascii_distro PacBSD"
alias ubuntu="sudo chroot /compat/ubuntu /bin/bash"

___MY_VMOPTIONS_SHELL_FILE="${HOME}/.jetbrains.vmoptions.sh"; if [ -f "${___MY_VMOPTIONS_SHELL_FILE}" ]; then . "${___MY_VMOPTIONS_SHELL_FILE}"; fi
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
