#-----------------------------------------------
#                   OPTIONS
#-----------------------------------------------
[options]
    colorscheme = "onedark"
#   colorscheme = "SpaceVim"
#   colorscheme = "molokai-dark"
#   colorscheme = "monokai_pro"
#   colorscheme = "dracula"
    colorscheme_bg = "dark"
    enable_guicolors = true
    rainbow_active = 1

#   statusline_separator = "nil"
    statusline_separator = "arrow"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode = false
    vimcompatible = true
    default_indent = 4

    lint_on_the_fly = true
    automatic_update = true
    filetree_direction = "left"

[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"
[[layers]]
    name = "checkers" 
[[layers]]
    name = "format"
#   format_method = "codefmt"
    format_on_save = true
    silent_format = true
    enable = true
[[layers]]
    name = "colorscheme"
    random_theme = false

#-----------------------------------------------
#              LANGUAGE SUPPORT
#-----------------------------------------------
[[layers]]
    name = 'lang#c'
    enable_clanng_syntax_highlight = true
#   format_on_save = true
    default_indent = 4
    [layer.clang_std]
        cpp = 'c11'
# rustup component add rls rust-analysis rust-src
[[layers]]
    name = "lang#rust"
    [[layers]]
    name = "lsp"
    filetypes = [
        "rust"
    ]
    [layers.override_cmd]
        rust = ["rls"]
# cpanm Perl::Critic
[[layers]]
    name = "lang#perl"
[[layers]]
    name = "lang#go"
    name = "format"
[[layers]]
    name = "lang#haskell"
[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 30

#-----------------------------------------------
#             CUSTOM PLUGINS
#-----------------------------------------------
[[custom_plugins]]
    repo = "https://github.com/frazrepo/vim-rainbow"
    merged = 0
[[custom_plugins]]
    repo = "https://github.com/airblade/vim-gitgutter"
    merged = 0
[[custom_plugins]]
    repo = "https://github.com/pR0Ps/molokai-dark"
    merged = 0
[[custom_plugins]]
    repo = "https://github.com/phanviet/vim-monokai-pro"
    merged = 0
